Escape any double quotes in secret values

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -151,6 +151,28 @@ jobs:
               exit 1
             fi
 
+  command-test-load-secret-with-double-quotes:
+    docker:
+      - image: cimg/base:current
+    steps:
+      - checkout
+      # Run your orb's commands to validate them.
+      - doppler-circleci/install
+      - doppler-circleci/load_secrets:
+          doppler_token: DOPPLER_TOKEN_DOUBLE_QUOTES
+      - run:
+          name: Assert environment variables set up as expected
+          command: |
+            source $BASH_ENV
+            echo "${SECRET_WITH_DOUBLE_QUOTES}"
+            expected_value='This is a "test string" which contains "double quotes"'
+            if [ "${SECRET_WITH_DOUBLE_QUOTES}" != "${expected_value}" ]
+            then
+              echo "Test failed: SECRET_WITH_DOUBLE_QUOTES has not been set as expected."
+              exit 1
+            fi
+
+
 workflows:
   test-deploy:
     jobs:
@@ -168,6 +190,9 @@ workflows:
       - command-test-load-multiline_secret:
           context: circleci-orb-publishing
           filters: *filters
+      - command-test-load-secret-with-double-quotes:
+          context: circleci-orb-publishing
+          filters: *filters
       # The orb must be re-packed for publishing, and saved to the workspace.
       - orb-tools/pack:
           filters: *release-filters
@@ -182,5 +207,6 @@ workflows:
             - command-test-apk
             - command-test-load-secrets-from-two-configs
             - command-test-load-multiline_secret
+            - command-test-load-secret-with-double_quotes
           context: circleci-orb-publishing
           filters: *release-filters
