Merged install of jq into load_secrets.sh and added multiline secret test

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -127,6 +127,26 @@ jobs:
               echo "Test failed: SECRET_B1 has not been set."
               exit 1
             fi
+
+  command-test-load-multiline_secret:
+    docker:
+      - image: cimg/base:current
+    steps:
+      - checkout
+      # Run your orb's commands to validate them.
+      - doppler-circleci/install
+      - doppler-circleci/load_secrets:
+          doppler_token: DOPPLER_TOKEN_MULTI_LINE
+      - run:
+          name: Assert environment variables set up as expected
+          command: |
+            source $BASH_ENV
+            if [ "${MULTI_LINE_SECRET}" != "1\n2\n3" ]
+            then
+              echo "Test failed: MULTI_LINE_SECRET has not been set as expected."
+              exit 1
+            fi
+
 workflows:
   test-deploy:
     jobs:
@@ -154,5 +174,6 @@ workflows:
             - command-test-apt
             - command-test-apk
             - command-test-load-secrets-from-two-configs
+            - command-test-load-multiline_secret
           context: circleci-orb-publishing
           filters: *release-filters
