Add tests for secrets sourced from multiple configs

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -39,6 +39,11 @@ jobs:
               echo "Test failed: SUPER_SECRET_PASSWORD has not been set."
               exit 1
             fi
+            if [ -z "$SUPER_SECRET_KEY" ]
+            then
+              echo "Test failed: SUPER_SECRET_KEY has not been set."
+              exit 1
+            fi
             if [ "$DOPPLER_PROJECT" ]
             then
               echo "Test failed: DOPPLER_PROJECT has been set."
@@ -92,6 +97,14 @@ jobs:
               exit 1
             fi
             echo "All tests passed."
+      - run:
+          name: Assert environment variables set up as expected
+          command: |
+            if [ -z "$SUPER_SECRET_PASSWORD" ]
+            then
+              echo "Test failed: SUPER_SECRET_PASSWORD has not been set."
+              exit 1
+            fi
 
   command-test-load-secrets-from-two-configs:
     docker:
@@ -104,7 +117,19 @@ jobs:
           doppler_token: DOPPLER_TOKEN
       - doppler-circleci/load_secrets:
           doppler_token: DOPPLER_TOKEN_2
-
+      - run:
+          name: Assert environment variables set up as expected
+          command: |
+            if [ -z "$SUPER_SECRET_PASSWORD" ]
+            then
+              echo "Test failed: SUPER_SECRET_PASSWORD has not been set."
+              exit 1
+            fi
+            if [ -z "$TEST_SECRET" ]
+            then
+              echo "Test failed: SUPER_SECRET_KEY has not been set."
+              exit 1
+            fi
 workflows:
   test-deploy:
     jobs:
