Add --no-read-env option and tess for loading secrets for 2 configs

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -56,6 +56,18 @@ jobs:
             fi
             echo "All tests passed."
 
+  command-test-load-secrets-twice:
+    docker:
+      - image: cimg/base:current
+    steps:
+      - checkout
+      # Run your orb's commands to validate them.
+      - doppler-circleci/install
+      - doppler-circleci/load_secrets:
+          doppler_token: DOPPLER_TOKEN
+      - doppler-circleci/load_secrets:
+          doppler_token: DOPPLER_TOKEN_2
+
   command-test-apk:
     docker:
       - image: alpine:latest
@@ -67,12 +79,40 @@ jobs:
       - run:
           name: Print out doppler secret as an environment variable
           command: source $BASH_ENV && echo -e "${SUPER_SECRET_PASSWORD}"
+      - run:
+          name: Assert environment variables set up as expected
+          command: |
+            if [ -z $SUPER_SECRET_PASSWORD ]
+            then
+              echo "Test failed: SUPER_SECRET_PASSWORD has not been set."
+              exit 1
+            fi
+            if [ $DOPPLER_PROJECT ]
+            then
+              echo "Test failed: DOPPLER_PROJECT has been set."
+              exit 1
+            fi
+            if [ $DOPPLER_CONFIG ]
+            then
+              echo "Test failed: DOPPLER_CONFIG has been set."
+              exit 1
+            fi
+            if [ $DOPPLER_ENVIRONMENT ]
+            then
+              echo "Test failed: DOPPLER_ENVIRONMENT has been set."
+              exit 1
+            fi
+            echo "All tests passed."
+
 workflows:
   test-deploy:
     jobs:
       # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
       # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
       - command-test-apt:
+          context: circleci-orb-publishing
+          filters: *filters
+      - command-test-load-secrets-twice:
           context: circleci-orb-publishing
           filters: *filters
       - command-test-apk:
@@ -90,5 +130,6 @@ workflows:
             - orb-tools/pack
             - command-test-apt
             - command-test-apk
+            - command-load-secrets-twice
           context: circleci-orb-publishing
           filters: *release-filters
